#server:
#  port: 9001

spring:
  datasource:
    url: jdbc:mysql://192.168.56.101:3309/micro_users?verifyServerCertificate=false&useSSL=true
    username: xiaoc
    password: xroot
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: users
eureka:
  client:
    service-url:
      defaultZone: http://192.168.56.101:5607/eureka/
  instance:
     leaseRenewalIntervalInSeconds: 1
     leaseExpirationDurationInSeconds: 2
